// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snweganwnjsuelzafuae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNud2VnYW53bmpzdWVsemFmdWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwOTc0ODMsImV4cCI6MjA4NDY3MzQ4M30.vVGe2-oh_JJ2LD3GYv3cEvTs_NgcBnYVUavevkCTifQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
